using MediatR;
using Otantik.BuildingBlocks;
using OtantikPos.Inventory.Domain.RawMaterials;
using OtantikPos.Inventory.Domain.StockMovements;

namespace OtantikPos.Inventory.Application.RawMaterials;

// PurchaseId and StockCountId are generated by the client when the screen opens, not by the
// server. A cashier who taps Save twice on a flaky LAN, or a browser that retries, sends the
// same id again. The second request finds the movements already posted and changes nothing,
// so a delivery is never booked twice.

public sealed record ReceivePurchaseCommand(Guid PurchaseId, IReadOnlyList<PurchaseLine> Lines)
    : IRequest<IReadOnlyList<RawMaterialDto>>, IRetryOnConflict;

// Quantity in the material's own unit (grams, millilitres, pieces). Cost: what the line cost in
// all, from the invoice; it moves the material's average cost. Without it, only stock changes.
public sealed record PurchaseLine(Guid RawMaterialId, decimal Quantity, decimal? Cost = null);

internal sealed class ReceivePurchaseCommandHandler(
    IRawMaterialRepository materials,
    IStockMovementRepository movements,
    IUnitOfWork unitOfWork) : IRequestHandler<ReceivePurchaseCommand, IReadOnlyList<RawMaterialDto>>
{
    public async Task<IReadOnlyList<RawMaterialDto>> Handle(ReceivePurchaseCommand request, CancellationToken cancellationToken)
    {
        var byId = await materials.GetRequiredByIdsAsync(
            request.Lines.Select(l => l.RawMaterialId).ToList(), cancellationToken);

        if (!await movements.ExistsAsync(request.PurchaseId, StockMovementReason.Purchase, cancellationToken))
        {
            foreach (var line in request.Lines)
                movements.Add(byId[line.RawMaterialId].ReceivePurchase(line.Quantity, request.PurchaseId, line.Cost));

            await unitOfWork.SaveChangesAsync(cancellationToken);
        }

        return byId.Values.Select(RawMaterialDto.From).ToList();
    }
}

// Thrown-away raw stock, as a manager records it. SpoilageId works as PurchaseId does, and
// RecordedBy is set by the API from who is signed in.
public sealed record RecordSpoilageCommand(Guid SpoilageId, IReadOnlyList<SpoilageLine> Lines, string RecordedBy = "")
    : IRequest<IReadOnlyList<RawMaterialDto>>, IRetryOnConflict;

// Quantity in the material's own unit. Reason: expired, spoiled, dropped, damaged packaging.
public sealed record SpoilageLine(Guid RawMaterialId, decimal Quantity, string Reason);

internal sealed class RecordSpoilageCommandHandler(
    IRawMaterialRepository materials,
    IStockMovementRepository movements,
    IUnitOfWork unitOfWork) : IRequestHandler<RecordSpoilageCommand, IReadOnlyList<RawMaterialDto>>
{
    public async Task<IReadOnlyList<RawMaterialDto>> Handle(RecordSpoilageCommand request, CancellationToken cancellationToken)
    {
        var byId = await materials.GetRequiredByIdsAsync(
            request.Lines.Select(l => l.RawMaterialId).ToList(), cancellationToken);

        if (!await movements.ExistsAsync(request.SpoilageId, StockMovementReason.Spoilage, cancellationToken))
        {
            foreach (var line in request.Lines)
                movements.Add(byId[line.RawMaterialId].RecordSpoilage(line.Quantity, request.SpoilageId, line.Reason, request.RecordedBy));

            await unitOfWork.SaveChangesAsync(cancellationToken);
        }

        return byId.Values.Select(RawMaterialDto.From).ToList();
    }
}
